// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/unitlink-nav/AddPropertyScreen.tsx": () => import("../components/mockups/unitlink-nav/AddPropertyScreen.tsx"),
  "./components/mockups/unitlink-nav/AssignDutyScreen.tsx": () => import("../components/mockups/unitlink-nav/AssignDutyScreen.tsx"),
  "./components/mockups/unitlink-nav/BottomTabs.tsx": () => import("../components/mockups/unitlink-nav/BottomTabs.tsx"),
  "./components/mockups/unitlink-nav/ChatFullScreen.tsx": () => import("../components/mockups/unitlink-nav/ChatFullScreen.tsx"),
  "./components/mockups/unitlink-nav/Current.tsx": () => import("../components/mockups/unitlink-nav/Current.tsx"),
  "./components/mockups/unitlink-nav/LandlordChatsScreen.tsx": () => import("../components/mockups/unitlink-nav/LandlordChatsScreen.tsx"),
  "./components/mockups/unitlink-nav/LandlordEmptyHomeScreen.tsx": () => import("../components/mockups/unitlink-nav/LandlordEmptyHomeScreen.tsx"),
  "./components/mockups/unitlink-nav/LandlordHomeScreen.tsx": () => import("../components/mockups/unitlink-nav/LandlordHomeScreen.tsx"),
  "./components/mockups/unitlink-nav/LandlordRoomScreen.tsx": () => import("../components/mockups/unitlink-nav/LandlordRoomScreen.tsx"),
  "./components/mockups/unitlink-nav/LandlordSettingsScreen.tsx": () => import("../components/mockups/unitlink-nav/LandlordSettingsScreen.tsx"),
  "./components/mockups/unitlink-nav/LandlordSingleHomeScreen.tsx": () => import("../components/mockups/unitlink-nav/LandlordSingleHomeScreen.tsx"),
  "./components/mockups/unitlink-nav/LoginScreen.tsx": () => import("../components/mockups/unitlink-nav/LoginScreen.tsx"),
  "./components/mockups/unitlink-nav/NewPropertyScreen.tsx": () => import("../components/mockups/unitlink-nav/NewPropertyScreen.tsx"),
  "./components/mockups/unitlink-nav/NewPropertyScreenPremium.tsx": () => import("../components/mockups/unitlink-nav/NewPropertyScreenPremium.tsx"),
  "./components/mockups/unitlink-nav/PillSegments.tsx": () => import("../components/mockups/unitlink-nav/PillSegments.tsx"),
  "./components/mockups/unitlink-nav/PropertyScreenWarm.tsx": () => import("../components/mockups/unitlink-nav/PropertyScreenWarm.tsx"),
  "./components/mockups/unitlink-nav/RequestDetailScreen.tsx": () => import("../components/mockups/unitlink-nav/RequestDetailScreen.tsx"),
  "./components/mockups/unitlink-nav/RoleSelectScreen.tsx": () => import("../components/mockups/unitlink-nav/RoleSelectScreen.tsx"),
  "./components/mockups/unitlink-nav/SignUpScreen.tsx": () => import("../components/mockups/unitlink-nav/SignUpScreen.tsx"),
  "./components/mockups/unitlink-nav/TenantEmptyHomeScreen.tsx": () => import("../components/mockups/unitlink-nav/TenantEmptyHomeScreen.tsx"),
  "./components/mockups/unitlink-nav/TenantHomeScreen.tsx": () => import("../components/mockups/unitlink-nav/TenantHomeScreen.tsx"),
  "./components/mockups/unitlink-nav/TenantProfileScreen.tsx": () => import("../components/mockups/unitlink-nav/TenantProfileScreen.tsx"),
  "./components/mockups/unitlink-nav/TenantSettingsScreen.tsx": () => import("../components/mockups/unitlink-nav/TenantSettingsScreen.tsx"),
  "./components/mockups/unitlink-nav/UnitScreen.tsx": () => import("../components/mockups/unitlink-nav/UnitScreen.tsx")
};
