import { StyleSheet } from 'react-native';
import { Theme } from '../../constants/theme';

export const C = {
  bg: "#F8FAFC", card: "#FFFFFF", fg: "#0F172A", muted: "#F1F5F9",
  mutedFg: "#64748B", border: "#E2E8F0", primary: "#2563EB",
  accent: "#EFF6FF", success: "#10B981", warning: "#F59E0B",
  danger: "#EF4444", g1: "#1D4ED8", g3: "#3B82F6",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 16,
    color: C.mutedFg,
    marginBottom: 16,
  },
  backButtonFallback: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: C.primary,
    borderRadius: 8,
  },
  backButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  
  // Header
  header: {
    backgroundColor: C.card,
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderColor: C.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  headerIconButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: C.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIconText: {
    fontSize: 16,
    color: C.mutedFg,
  },
  headerTitleContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: C.fg,
    letterSpacing: -0.4,
  },
  headerSubtitle: {
    fontSize: 12,
    color: C.mutedFg,
    marginTop: 1,
  },

  // Main Content
  mainContent: {
    flex: 1,
    position: 'relative',
  },
  tabContent: {
    flex: 1,
  },
  tabContentContainer: {
    paddingBottom: 20,
  },

  // Hero Card
  heroWrapper: {
    paddingTop: 14,
    paddingHorizontal: 16,
  },
  heroGradient: {
    borderRadius: 18,
    paddingTop: 16,
    paddingHorizontal: 18,
    paddingBottom: 16,
    position: 'relative',
    overflow: 'hidden',
  },
  heroCircle: {
    position: 'absolute',
    right: -20,
    top: -20,
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  heroMonthText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: 'rgba(255,255,255,0.8)',
  },
  heroAmountCollected: {
    fontSize: 24,
    fontWeight: '800',
    color: '#fff',
    marginTop: 2,
  },
  heroAmountTotal: {
    fontSize: 13,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.75)',
  },
  heroBadge: {
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  heroBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#fff',
  },
  heroProgressBarContainer: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
    marginBottom: 10,
  },
  heroProgressBarFill: {
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 2,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 24,
  },
  heroStatLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
  },
  heroStatValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#fff',
  },

  // Lists
  listContainer: {
    paddingTop: 14,
    paddingHorizontal: 16,
    gap: 10,
  },
  listItemCard: {
    backgroundColor: C.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  listItemIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: C.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listItemIconText: {
    fontSize: 18,
    color: C.primary,
  },
  listItemTextContainer: {
    flex: 1,
  },
  listItemTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: C.fg,
  },
  listItemSubtitle: {
    fontSize: 12,
    color: C.mutedFg,
    marginTop: 1,
  },
  tenantAvatarsContainer: {
    flexDirection: 'row-reverse',
    marginRight: 4,
  },
  tenantAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tenantAvatarText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#fff',
  },
  chevronIcon: {
    fontSize: 18,
    color: C.border,
  },

  // Rent Tab Specifics
  rentActionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 4,
  },
  rentActionOutline: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.card,
    alignItems: 'center',
  },
  rentActionOutlineText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.fg,
  },
  rentActionPrimary: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: C.primary,
    alignItems: 'center',
  },
  rentActionPrimaryText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
  },
  statusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },

  // Floating Actions
  fabContainerCenter: {
    position: 'absolute',
    bottom: 18,
    left: 0,
    right: 0,
    alignItems: 'center',
    pointerEvents: 'box-none',
  },
  fabPrimary: {
    paddingVertical: 13,
    paddingHorizontal: 26,
    borderRadius: 28,
    backgroundColor: C.primary,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 8,
  },
  fabPrimaryText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: Theme.fonts.bold,
  },
  updatesSegmentContainer: {
    flexDirection: 'row',
    backgroundColor: C.muted,
    borderRadius: 12,
    padding: 4,
    marginHorizontal: 16,
    marginTop: 16,
  },
  updatesSegmentBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  updatesSegmentBtnActive: {
    backgroundColor: C.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  updatesSegmentText: {
    fontSize: 13,
    fontWeight: '600',
    color: C.mutedFg,
  },
  updatesSegmentTextActive: {
    fontWeight: '700',
    color: C.primary,
  },
  requestsBadge: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  requestsBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#fff',
  },
  weekHeader: {
    backgroundColor: C.accent,
    borderRadius: 14,
    padding: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  weekHeaderTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: C.primary,
  },
  weekHeaderDate: {
    fontSize: 11,
    color: '#1D4ED8',
    marginTop: 2,
  },
  weekHeaderBadge: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: C.primary,
  },
  weekHeaderBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#fff',
  },
  assignChoreBtn: {
    backgroundColor: C.primary,
    borderRadius: 14,
    padding: 13,
    alignItems: 'center',
    marginBottom: 16,
  },
  assignChoreBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  choreCard: {
    backgroundColor: C.card,
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: 10,
  },
  choreMainRow: {
    padding: 13,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  choreIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: C.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choreIcon: {
    fontSize: 18,
  },
  choreInfo: {
    flex: 1,
  },
  choreName: {
    fontSize: 14,
    fontWeight: '800',
    color: C.fg,
  },
  choreStatusBadge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 20,
  },
  choreStatusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  choreSchedule: {
    fontSize: 11,
    color: C.mutedFg,
  },
  choreCurrentAssignee: {
    alignItems: 'center',
    gap: 2,
  },
  choreAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choreAvatarText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#fff',
  },
  choreCurrentName: {
    fontSize: 9,
    color: C.mutedFg,
    fontWeight: '600',
  },
  choreExpanded: {
    borderTopWidth: 1,
    borderTopColor: C.border,
    padding: 12,
    paddingHorizontal: 14,
    backgroundColor: C.muted,
  },
  rotationTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: C.mutedFg,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  rotationIndexBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rotationIndexText: {
    fontSize: 9,
    fontWeight: '800',
  },
  rotationAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rotationAvatarText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#fff',
  },
  rotationName: {
    fontSize: 12,
  },
  rotationRoom: {
    fontSize: 11,
    color: C.mutedFg,
  },
  thisWeekBadge: {
    backgroundColor: C.accent,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 20,
  },
  thisWeekText: {
    fontSize: 10,
    fontWeight: '700',
    color: C.primary,
  },
  choreActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  editChoreBtn: {
    flex: 1,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.card,
    alignItems: 'center',
  },
  editChoreBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.fg,
  },
  deleteChoreBtn: {
    flex: 1,
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
  },
  deleteChoreBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#EF4444',
  },
  annCard: {
    backgroundColor: C.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    padding: 16,
    marginBottom: 12,
  },
  annHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  annHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  annIcon: {
    fontSize: 16,
  },
  annDate: {
    fontSize: 12,
    color: C.mutedFg,
  },
  annBadge: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
  },
  annBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  annTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: C.fg,
    marginBottom: 6,
    fontFamily: Theme.fonts.bold,
  },
  annBody: {
    fontSize: 13,
    color: C.mutedFg,
    lineHeight: 20,
    marginBottom: 16,
    fontFamily: Theme.fonts.regular,
  },
  annFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: C.border,
    paddingTop: 12,
  },
  annActions: {
    flexDirection: 'row',
    gap: 16,
  },
  annActionEditText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.mutedFg,
  },
  annActionDeleteText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.danger,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: C.fg,
    fontFamily: Theme.fonts.bold,
  },
  modalCloseText: {
    fontSize: 20,
    color: C.mutedFg,
    paddingHorizontal: 8,
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: C.mutedFg,
    marginBottom: 8,
    marginTop: 16,
    textTransform: 'uppercase',
    fontFamily: Theme.fonts.bold,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: C.fg,
    fontFamily: Theme.fonts.regular,
  },
  modalInputArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  expiryOptionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  expiryBtn: {
    flex: 1,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 10,
    alignItems: 'center',
  },
  expiryBtnActive: {
    borderColor: C.primary,
    backgroundColor: C.accent,
  },
  expiryBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.mutedFg,
    fontFamily: Theme.fonts.bold,
  },
  expiryBtnTextActive: {
    color: C.primary,
  },
  modalSaveBtn: {
    backgroundColor: C.primary,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 24,
  },
  modalSaveBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: Theme.fonts.bold,
  },
  fabContainerRight: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    alignItems: 'center',
    gap: 4,
  },
  fabChat: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 16,
    elevation: 6,
  },
  fabChatIcon: {
    fontSize: 22,
  },
  fabChatBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: C.danger,
    borderWidth: 2,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabChatBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#fff',
  },
  fabChatLabel: {
    fontSize: 9,
    color: C.mutedFg,
    fontWeight: '600',
    letterSpacing: 0.3,
  },

  // Bottom Tabs
  bottomTabBar: {
    backgroundColor: C.card,
    borderTopWidth: 1,
    borderColor: C.border,
    paddingTop: 10,
    paddingHorizontal: 12,
  },
  bottomTabGroup: {
    backgroundColor: C.muted,
    borderRadius: 14,
    padding: 4,
    flexDirection: 'row',
    gap: 3,
  },
  bottomTabButton: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 10,
    alignItems: 'center',
    position: 'relative',
  },
  bottomTabButtonActive: {
    backgroundColor: C.card,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  bottomTabText: {
    fontSize: 12,
    fontWeight: '500',
    color: C.mutedFg,
  },
  bottomTabTextActive: {
    fontWeight: '700',
    color: C.primary,
  },
  bottomTabBadge: {
    position: 'absolute',
    top: 3,
    right: 6,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: C.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomTabBadgeText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#fff',
  },
  snackbar: {
    position: 'absolute',
    bottom: 90,
    left: 16,
    right: 16,
    backgroundColor: '#333',
    padding: 14,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 999,
  },
  snackbarText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
});
